labels:
- name: bug
  description: 'Something isn''t working'
  color: 'd73a4a'
- name: new_label
  color: '898989'
- name: new_label_desc
  description: 'Label with a Description'
  color: '666666'
- name: approved
  color: 00FF00
- name: rejected
  color: FF0000
- name: 'target: main'
  color: FFFFFF
- name: 'target: release/*'
  color: 0000FF