requiredApprovals: 1
labels:
  approved: 'approved'
  rejected: 'rejected'
  needsReview: 'needs-review'
branchLabeller:
- target: 'main'
  startsWith: false
  label: 'target: main'
- target: 'release/'
  startsWith: true
  label: 'target: release/*'