name: 'Label Sync'
on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/label-sync.yml
    - .github/label-sync.yml

jobs:
  label-sync:
    name: 'Sync Labels'
    runs-on: ubuntu-latest
    steps:
    - uses: DrBarnabus/github-label-sync@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        owner: DrBarnabus
        repo: label-testing
